# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/use
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.4

# Mod Properties
mod_version = 1.2.0
maven_group = com.vladmarica
archives_base_name = BetterPingDisplay-Fabric

# Dependencies
fabric_version=0.140.2+1.21.11
modmenu_version=17.0.0-beta.1
cloth_config_version=21.11.153
yacl_version=3.8.1+1.21.11-fabric
