# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/use
minecraft_version=26.1
loader_version=0.18.4

# Mod Properties
mod_version = 1.2.0
maven_group = com.vladmarica
archives_base_name = BetterPingDisplay-Fabric

# Dependencies
fabric_version=0.144.3+26.1
modmenu_version=18.0.0-alpha.7
yacl_version=3.9.0+26.1-fabric
