# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/use
minecraft_version=26.1.2
loader_version=0.16.0

# Mod Properties
mod_version = 1.2.0
maven_group = com.vladmarica
archives_base_name = BetterPingDisplay-Fabric

# Dependencies
fabric_version=0.145.4+26.1.2
modmenu_version=18.0.0-beta.1
cloth_config_version=26.1.154
yacl_version=3.9.4+26.1-fabric
